# Global Configs
[config]
version_check = false

##################
# Input / Output #
##################

# Kitty
[templates.kitty]
input_path = '~/.config/matugen/templates/matugen-kitty.conf'
output_path = '~/.config/kitty/matugen/colors-matugen.conf'

# Nvim
[templates.nvim]
input_path = '~/.config/matugen/templates/matugen-nvim.conf'
output_path = '~/.config/nvim/matugen/matugen-nvim.conf'

# Rofi
[templates.rofi]
input_path = '~/.config/matugen/templates/matugen-rofi.rasi'
output_path = '~/.config/rofi/matugen/matugen-rofi.rasi'

# Waybar
[templates.waybar]
input_path = '~/.config/matugen/templates/matugen-waybar.css'
output_path = '~/.config/waybar/matugen/matugen-waybar.css'
post_hook = 'pkill -SIGUSR2 waybar'

# Mako
[templates.mako]
input_path = '~/.config/matugen/templates/matugen-mako.conf'
output_path = '~/.config/mako/colors'
post_hook = 'makoctl reload'

# Swaync
[templates.swaync]
input_path = '~/.config/matugen/templates/matugen-swaync.css'
output_path = '~/.config/swaync/matugen/matugen-swaync.css'
post_hook = 'swaync-client -rs'
